// Auto-Generated by FAKE; do not edit
namespace System
open System.Runtime.CompilerServices

[<assembly: InternalsVisibleToAttribute("StringCalculator.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] InternalsVisibleTo = "StringCalculator.Tests"
